//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rusada_Mvc_Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Aircraft
    {
        public int id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string registration { get; set; }
        public string location { get; set; }
        public System.DateTime date { get; set; }
        public string image_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
